### ISSUE TITLE
CSS Conflict with daisyUI: status class

### ISSUE THREAD

**Issue by Strehk** [kbrgl/svelte-french-toast#103]
Hey, I just discovered a css class conflict with [daisyUI](https://daisyui.com/). The `status` class is adding a weird padding to the icon which makes it offset.

Since I want to use the daisyUI status, I'd like the class in this library to be changed to something more unique, like `toast-status`.

Would that be possible? I can open a PR for that for sure

**Comment by azzurro** [comment]
I encountered that issue as well.

Workaround: exclude the status component from DaisyUI:

```
@plugin "daisyui" {
    themes: light --default;
    exclude: status;
}
```

**Comment by itschasa** [comment]
have this issue too

**Comment by itschasa** [comment]
@Strehk try add this to your app.css, worked for me
```css
.toaster > .wrapper > .base > .indicator > .status {
  height: auto!important;
  width: auto!important;
}
```
